[package]
name = "gores-mapgen"
version = "1.0.6-beta"
edition = "2021"
default-run = "editor"

[[bin]]
name = "editor"

[[bin]]
name = "config_points"

[[bin]]
name = "benchmark"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
indicatif = { version = "0.17.8", optional = true }

# [patch.crates-io]
# rand = { version = "0.8.5", default-features = false }

[dependencies]
#getrandom = { version = "=0.2.16", default-features = false }
egui-macroquad = "0.17.3"
egui = "0.31.1"
egui-miniquad = "0.16.0"
egui-file-dialog = "0.9.0"
egui-notify = "0.19"
macroquad = "0.4.14"
# ndarray = "0.15.6"
ndarray = "0.16.1"
rand = {version="0.8.5", features=['small_rng'], default-features = false}
seahash = "4.1.0"
rand_distr = "0.4.3"
# twmap = "0.12.0"
twmap = { git="https://gitlab.com/iMilchshake/twmap.git" }
clap = { version = "4.5.4", features = ["derive", "cargo"] }
serde = "1.0.197"
serde_json = "1.0.115"
rust-embed = { version = "8.3.0", features = ["debug-embed"] }
num = "0.4"
derivative = "2.2.0"
log = "0.4.22"
simple_logger = "5.0.0"
base64 = "0.22.1"
seed_gen = "1.1.0"
noise = "0.9.0"
rand_xoshiro = { version = "0.6", default-features = false }

[dev-dependencies]
insta = "1.40"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "fat"                     # enable link time optimization
strip = true                    # strip debug symbols
codegen-units = 1               # use a single codegen-unit for better optimizations
